[villager]
title = "村民"
[villager.fields]
id.type = "number"
id.auto-increment = true
branchId.title = "所属支部"
branchId.ref = "branch.id"
branchId."$ui".label = "branch.name"
groupId.title = "所属小组"
groupId.ref = "group.id"
groupId."$ui".label = "group.name"
name.title = "姓名"
name.type = "string"
name.required = true
phone.title = "手机号码"
phone.type = "string"
phone.format = "^1((34[0-8])|(8\\d{2})|(([0-35-9]|4|66|7|9)\\d{1}))\\d{7}$"
politicalStatusCode.title = "政治身份"
politicalStatusCode.required = true
politicalStatusCode.ref = "dict.({name: 'political_status'}).value"
politicalStatusCode."$ui".label = "dict.text"
representativeCode.title = "村民代表"
representativeCode.required = true
representativeCode.ref = "dict.({name: 'representative'}).value"
representativeCode."$ui".label = "dict.text"
examineRequiredCode.title = "参与党员考核"
examineRequiredCode.required = true
examineRequiredCode.ref = "dict.({name: 'examine_required'}).value"
examineRequiredCode."$ui".label = "dict.text"
address.title = "地址"
address.type = "string"
address.maxLength = 200
address.indexed = false

[dict]
title = "字典表"
many = false
[dict.fields]
id.type = "number"
id.auto-increment = true
[dict.fields.type]
title = "类型"
type = "string"
required = true
[dict.fields.text]
title = "名称"
type = "string"
required = true
[dict.fields.value]
title = "值"
type = "string"
required = true

[branch]
title = "分支"
[branch.fields]
id.type = "number"
id.auto-increment = true
name.title = "名称"
name.type = "string"
name.required = true

[group]
title = "小组"
[group.fields]
id.type = "number"
id.auto-increment = true
branchId.ref = "branch.id"
branchId."$ui".label = "branch.name"
name.title = "名称"
name.type = "string"
name.required = true

# [volunteer-service]
# id.type = "number"
# id.auto-increment = true
# [volunteer-service.start_time]
# title = "开始时间"
# type = "datetime"
# required = true
# [volunteer-service.start_time."$ui"]
# format = "YYYY/MM/DD HH:mm:ss"
# [volunteer-service.end_time]
# title = "结束时间"
# type = "datetime"
# required = true
# [volunteer-service.end_time."$ui"]
# format = "YYYY/MM/DD HH:mm:ss"
# [volunteer-service.score]
# title = "分数"
# type = "number"
# precision = 0
# min = 0
# max = 10

# [domicile]
# id.type = "number"
# id.auto-increment = true
# branchId.ref = "branch.id"
# groupId.ref = "group.id"
# name.title = "名称"
# name.type = "string"
# name.required = true

# [domicile-visit]
# id.type = "number"
# id.auto-increment = true
# domicileId.ref = "domicile.id"
# domicileId.required = true
# villagerId.ref = "villager.id"
# villagerId.required = true
# visit_time.title = "走访时间"
# visit_time.type = "date"
# visit_time.format = "YYYY/MM/DD HH:mm:ss"
# visit_time.required = true
# remark.title = "村民反馈"
# remark.type = "string"