[villager]
id.type = number
id.auto-increment = true
branch.ref = branch.id
group.ref = group.id
name.title = 姓名
name.type = string
name.required = true
phone.title = 手机号码
phone.type = string
phone.format = "^1((34[0-8])|(8\\d{2})|(([0-35-9]|4|66|7|9)\\d{1}))\\d{7}$"
political_status.title = 政治身份
political_status.ref = "dict(name === 'political_status').value"
political_status.ref-text = "dict(name === 'political_status').text"
political_status.required = true
representative.title = 村民代表
representative.type = number
representative.values = {0 = 否, 1 = 是}
representative.required = true
examine_required.title = 参与考核
examine_required.type = number
examine_required.values = {0 = 否, 1 = 是}
examine_required.required = true
address.type = string
address.indexed = false

[dict]
id.type = number
id.auto-increment = true
type.type = string
type.required = true
text.type = string
text.required = true
value.type = string
value.required = true

[branch]
id.type = number
id.auto-increment = true
name.type = string
name.required = true

[group]
id.type = number
id.auto-increment = true
name.type = string
name.required = true
branchId.ref = branch.id

[volunteer-service]
id.type = number
id.auto-increment = true
start_time.type = date
start_time.required = true
end_time.type = date
end_time.required = true
score.type = number
score.precision = 0
score.min = 0
score.max = 10